Reject empty or too long labels.
Microsoft/AppCenter-Test-Appium-Java-Extensions pull request #2
Opened 2018-06-22 09:47 UTC by krukow

This PR rejects null or empty labels, and limits label length to 128 chars

2018-06-22 12:08 UTC, john7doe requested changes

2018-06-22 12:08 UTC, john7doe commented on src/main/java/com/microsoft/appcenter/appium/EnhancedAndroidDriver.java
> +        if (null == label || label.length() < 1 || label.length() > 128) {
I think this would be better located in the constructor of Event

2018-06-22 12:08 UTC, john7doe commented on src/test/java/com/microsoft/appcenter/appium/EnhancedAndroidDriverTest.java
> +        String longLabel = "longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong";
Consider this instead: (after the test is moved to EventTest.java :-)

        String longLabel = String.join("", Collections.nCopies(128, "a"));

2018-06-22 12:08 UTC, john7doe commented on src/test/java/com/microsoft/appcenter/appium/EnhancedAndroidDriverTest.java
> +            driver.label(longLabel + "1");
I prefer that one test tests one thing. So consider moving this to its own test

2018-06-29 10:37 UTC, kamstrup commented
Looks good to me. My main concern is if 128 chars is too restrictive. I've seen many clients using long step labels...

2018-06-29 10:43 UTC, kamstrup commented
(also noted on the espresso PR) - maybe we should add some thorough param validation in the Event constructor as well? Now that we are shaking things up here anyway...

2018-07-02 07:45 UTC, krukow commented
@kamstrup please re-review

2018-07-02 09:22 UTC, kamstrup approved these changes
Good stuff. I would still prefer truncating at 160 chars, but having a 256 hard cut is also ok by me if you prefer that.

2018-07-02 09:22 UTC, kamstrup commented on src/main/java/com/microsoft/appcenter/appium/Event.java
> +        }
I love you!

2018-07-02 09:22 UTC, kamstrup commented on src/main/java/com/microsoft/appcenter/appium/Event.java
> +        }
Didn't we decide to truncate when `label.length() > MAX_LABEL_SIZE` and not raise an exception? Although I can see that max length is now 256 which is more than enough for anyone!!! ;-P

2018-07-16 11:41 UTC, merged